name: release

on:
  push:
    paths:
    - ".github/workflows/release.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile report
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: main.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf
